[package]
name = "rillrate-py"
version = "0.2.9"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rillrate-py"
homepage = "https://github.com/rate-technology/rillrate-py"
documentation = "https://docs.rs/rillrate-py/"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "rillrate bindings for python"
categories = ["development-tools::debugging"]
keywords = ["logging"]

[lib]
name = "rillrate"
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.5.2"
pyo3 = "0.13.1"
rillrate = "0.18.0"

[features]
default = ["pyo3/extension-module"]
