[package]
name = "rillpy"
version = "0.1.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rillpy"
homepage = "https://github.com/rate-technology/rillpy"
description = "Python bindings for rill"
categories = ["development-tools::debugging"]
keywords = ["logging"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[lib]
name = "rillrate"
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.5.2"
pyo3 = { version = "0.13.1", features = ["extension-module"] }
rillrate = "0.12.0"
