[package]
name = "rillpy"
version = "0.1.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rillpy"
homepage = "https://github.com/rate-technology/rillpy"
description = "Python bindings for rill"
categories = ["development-tools::debugging"]
keywords = ["logging"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[lib]
name = "rillpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.12.4", features = ["extension-module"] }
rill = "0.6.0"
