[tool.poetry]
name = "rillrate"
version = "0.4.0"
description = "rillrate bindings for python"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rate-technology/rillrate-py"
keywords = ["logging"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
maturin = "==0.9.0"
pytest = "^6.1"
